name: 🐞 Bug Report
description: Create a new bug report.
title: '🐞 [BUG]: '
labels: [bug, needs-triage]
project: ["default"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: 'Please [search :mag: the issues](https://github.com/weslleymurdock/SharpLocalizr/issues) to check if this bug has already been reported.'
      options:
      - label: I have searched the existing issues
        required: true
  
  - type: input
    attributes:
      label: Localizr version
      description: What Localizr version are you running?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe the problem you are experiencing. **Please do not paste your logs here.** Screenshots are welcome.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect to happen instead.
    validations:
      required: true

  - type: input
    attributes:
      label: Localizr Environment
      description: What Localizr environment are you running?
      value: |
          - [ ] Cloud
          - [ ] Self-Hosted
    validations:
      required: true


  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide additional information about your environment; feel free to remove any items which are not relevant.

        :warning: _Remember to redact or remove any sensitive information!_
      value: |
          - Last image version(s) which did _not_ exhibit the problem:

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide [the smallest, complete code snippet](https://stackoverflow.com/help/minimal-reproducible-example)
        that Ampere's maintainers can run to reproduce the issue.
        
        If the result is more than a screenful of text _or_ requires multiple files, please:

        - _Attach_ (do not paste) it to this textarea, _or_
        - Put it in a [Gist](https://gist.github.com) and paste the link, _or_
        - Provide a link to a new or existing public repository exhibiting the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Further Information
      description: If needed, please provide additional information about your issue (attachments, links, references, etc.).
