<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Localizr.Application\Localizr.Application.csproj" />
    <ProjectReference Include="..\Localizr.Composition\Localizr.Composition.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles;analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MudBlazor" Version="9.9.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.1" />
  </ItemGroup>

  <Target Name="AddMigration">
   <PropertyGroup>
     <MigrationOutput Condition="'$(MigrationOutput)' == ''">Persistence/Migrations</MigrationOutput>
     <IsVerbose Condition="'$(IsVerbose)' != ''">-v</IsVerbose>
   </PropertyGroup>
   <Error Condition="'$(Name)' == ''" Text="The 'Name' param is mandatory; Usage example: dotnet build -t:AddMigrationUI -p:Name=MyMigration" />
   <Message Text="Running: dotnet ef migrations add $(Name) --framework net10.0-windows10.0.19041.0 --output-dir $(MigrationOutput)" Importance="High" />
   <Exec Command="dotnet ef migrations add $(Name) --project .\..\Localizr.Infrastructure\ --startup-project . --output-dir $(MigrationOutput) $(IsVerbose)" ContinueOnError="false" />
   <Message Text="Migration process completed!" Importance="High" />
  </Target>

</Project>
