namespace Localizr.Application.Identity.Responses;


/// <summary>Represents the access and refresh tokens issued to an authenticated user.</summary>
/// <param name="TokenType">The HTTP authorization scheme for the access token.</param>
/// <param name="AccessToken">The issued access token.</param>
/// <param name="ExpiresIn">The access-token lifetime in seconds.</param>
/// <param name="RefreshToken">The issued refresh token.</param>
public sealed record TokenResponse(
    string TokenType,
    string AccessToken,
    int ExpiresIn,
    string RefreshToken);

/// <summary>Represents the result of an identity operation that does not return data.</summary>
/// <param name="Succeeded">Indicates whether the operation succeeded.</param>
/// <param name="Errors">The errors returned by the operation.</param>
public sealed record IdentityResultResponse(bool Succeeded, IReadOnlyCollection<string> Errors) 
{
    /// <summary>Creates a successful identity result.</summary>
    /// <returns>A successful result without errors.</returns>
    public static IdentityResultResponse Success() => new(true, []);

    /// <summary>Creates a failed identity result.</summary>
    /// <param name="errors">The errors describing the failure.</param>
    /// <returns>A failed result.</returns>
    public static IdentityResultResponse Failure(IEnumerable<string> errors) => new(false, errors.ToArray());
}

/// <summary>Represents basic identity information exposed to the authenticated user.</summary>
/// <param name="Email">The user's email address.</param>
/// <param name="IsEmailConfirmed">Indicates whether the email address is confirmed.</param>
public sealed record IdentityInfoResponse(string Email, bool IsEmailConfirmed);

/// <summary>Represents the current authenticator-based two-factor configuration.</summary>
/// <param name="SharedKey">The authenticator shared key, when available.</param>
/// <param name="RecoveryCodesLeft">The number of unused recovery codes.</param>
/// <param name="RecoveryCodes">New recovery codes generated by the operation, when requested.</param>
/// <param name="IsTwoFactorEnabled">Indicates whether two-factor authentication is enabled.</param>
/// <param name="IsMachineRemembered">Indicates whether the current machine is remembered.</param>
public sealed record TwoFactorResponse(
    string? SharedKey,
    int RecoveryCodesLeft,
    IReadOnlyCollection<string>? RecoveryCodes,
    bool IsTwoFactorEnabled,
    bool IsMachineRemembered);
